web:
  image: registry.aliyuncs.com/xianlu/test-link
  command: python test-link.py
  restart: always
  ports:
      - 5000
  links:
      - redis
  deploy:
      mode: global
redis:
  image: redis
  restart: always
